# Nixpacks configuration for Railway deployment

[phases.setup]
nixPkgs = ["python312", "postgresql"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[phases.build]
cmds = [
    "python manage.py collectstatic --no-input"
]

[start]
cmd = "python manage.py migrate && python manage.py populate_categories && gunicorn backend_api.wsgi --workers 3 --bind 0.0.0.0:$PORT"

