# Generated by Django 5.2.5 on 2025-09-22 22:14

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Event title', max_length=200)),
                ('description', models.TextField(help_text='Event description')),
                ('max_attendees', models.PositiveIntegerField(help_text='Maximum number of attendees', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10000)])),
                ('start_date', models.DateField(help_text='Event start date')),
                ('end_date', models.DateField(help_text='Event end date')),
                ('start_time', models.TimeField(help_text='Event start time')),
                ('end_time', models.TimeField(help_text='Event end time')),
                ('street', models.CharField(help_text='Street address', max_length=255)),
                ('city', models.CharField(help_text='City', max_length=100)),
                ('state', models.CharField(help_text='State/Province', max_length=100)),
                ('postal_code', models.CharField(help_text='Postal/ZIP code', max_length=20)),
                ('username', models.CharField(default='', help_text='Event host name', max_length=255)),
                ('email', models.EmailField(default='', help_text='Event contact email', max_length=254)),
                ('organizer_email', models.EmailField(default='', help_text='Event organizer email', max_length=254)),
                ('is_active', models.BooleanField(default=True, help_text='Whether the event is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'db_table': 'events',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=555)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'users',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EventImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Event image', upload_to='event_images/%Y/%m/%d/')),
                ('caption', models.CharField(blank=True, help_text='Image caption', max_length=255)),
                ('is_primary', models.BooleanField(default=False, help_text='Whether this is the primary image')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(help_text='Associated event', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='myapp.event')),
            ],
            options={
                'verbose_name': 'Event Image',
                'verbose_name_plural': 'Event Images',
                'db_table': 'event_images',
                'ordering': ['-is_primary', 'uploaded_at'],
            },
        ),
        migrations.AddField(
            model_name='event',
            name='organizer',
            field=models.ForeignKey(help_text='Event organizer', on_delete=django.db.models.deletion.CASCADE, related_name='organized_events', to='myapp.user'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['start_date', 'end_date'], name='events_start_d_92ba55_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['city', 'state'], name='events_city_0a7c0f_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['organizer'], name='events_organiz_1c7a2e_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['is_active'], name='events_is_acti_45ba60_idx'),
        ),
    ]
