# Generated by Django 5.0.14 on 2025-10-22 16:02

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_category_event_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(help_text='Rating from 1 to 5 stars', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True, help_text='Review comment/feedback')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(help_text='Event being reviewed', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='myapp.event')),
                ('host', models.ForeignKey(help_text='Host being reviewed (event organizer)', on_delete=django.db.models.deletion.CASCADE, related_name='received_reviews', to='myapp.user')),
                ('reviewer', models.ForeignKey(help_text='User who wrote the review', on_delete=django.db.models.deletion.CASCADE, related_name='given_reviews', to='myapp.user')),
            ],
            options={
                'verbose_name': 'Review',
                'verbose_name_plural': 'Reviews',
                'db_table': 'reviews',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event', '-created_at'], name='reviews_event_i_9316c9_idx'), models.Index(fields=['host', '-created_at'], name='reviews_host_id_a237f0_idx'), models.Index(fields=['reviewer'], name='reviews_reviewe_965d53_idx'), models.Index(fields=['rating'], name='reviews_rating_17e8a4_idx')],
                'unique_together': {('event', 'reviewer')},
            },
        ),
    ]
